name: Build and deploy Node.js app to Azure Web App - Studentregistrationapp

# Trigger on push to the main branch and allow manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Build Job
  build:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install Node.js dependencies
      - name: Install dependencies
        run: npm install
        working-directory: Frontend
      
      # Step 4: Build the application
      - name: Build application
        run: npm run build --if-present
        working-directory: Frontend

      # Step 5: Upload built artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: Frontend/dist

  # Deployment Job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for Azure JWT authentication

    steps:
      # Step 1: Download artifact from the build job
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: node-app

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ECB2611EF0E54228A8E1D6A5F21FBE3C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6DDD0BBC65AA46168C95F87AF3E60726 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AC6ACAE86A6B40C983B5927250717536 }}

      # Step 3: Deploy the application to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'mean-demo-model1'
          slot-name: 'Production'
          package: .
